### ISSUE TITLE
Using "prompt editing" ([from:to:when]) breaks prompt travel

### ISSUE THREAD

**Issue by lendrick** [Kahsolt/stable-diffusion-webui-prompt-travel#13]
When traveling between prompts that use prompt editing, it appears as if it's switching completely over to the original prompt when the prompt edit threshold is reached.  If the prompt edit happens very early on (like [red:blue:0.2]), barely anything changes until the last image.

**Comment by Kahsolt** [comment]
Regrettably but technically this extension cannot support `[from:to:when]` syntax in semantic sense (it just not getting error though), the condition must be a constant for each stage :(
To interpolate on a mutable condition requires step by step tracing at lower sampler/CFGDenoiser level, which is resource consuming and need more hard code hack (current webui hooks cannot do it), it be exhausted to maintain in face of webui's frequent updates.
