### ISSUE TITLE
Starting prompt travel before midnight but finishing after cause multiple date folder to be created and image numbering continuity is lost

### ISSUE THREAD

**Issue by axemaster** [Kahsolt/stable-diffusion-webui-prompt-travel#17]
I happened to run it over midnight and now my images are split into two folders (date-named) "2023-02-18" and "2023-02-19", and the second one restarted the image numbering at 00000.

Request is to keep the same initial output folder (and sequential numbering) is as created/used when the first image of the travel batch is saved.

Work around is to manually renumber and move everything. I'm glad this wasn't a big one.

If this is something the main UI controls and cannot be fixed in a script, please let me know so I can file an issue on that repo. I don't know if other scripts have this issue in common.
![Screenshot 2023-02-19 at 12 26 20 AM](https://user-images.githubusercontent.com/1783597/219937247-8a72b983-c5e1-48aa-9a82-f4476f6ec3ad.png)

**Comment by Kahsolt** [comment]
Interesting! 🤣 yet also a bit wired.. 🤔

When using all default settings for folder path and filename templates, the prompt-travel generated images are put under `<SD>\outputs\txt2img-images\prompt_travel\<travel_number>\*.png`, where `<travel_number>` is a zero-leading 5-digit like `00220`. It seems you used a customized filename template containing the time string. Or another extension overrided the saving paths maybe?

**Comment by axemaster** [comment]
> Interesting! 🤣 yet also a bit wired.. 🤔
> 
> When using all default settings for folder path and filename templates, the prompt-travel generated images are put under `<SD>\outputs\txt2img-images\prompt_travel\<travel_number>\*.png`, where `<travel_number>` is a zero-leading 5-digit like `00220`. It seems you used a customized filename template containing the time string. Or another extension overrided the saving paths maybe?

I don't know where that date stamp came from but I like it, except for weird stuff like this. I would prefer it set once at startup and not change while A111 is still running but I don't know where to file an issue on that.
