### ISSUE TITLE
use together with controlnet

### ISSUE THREAD

**Issue by loboere** [Kahsolt/stable-diffusion-webui-prompt-travel#18]
this is an awesome extension and it would be even more awesome if it could be used with controlnet

**Comment by Kahsolt** [comment]
Could you please tell me what extensions about controlnet you'll working with?
I would have an investigation whether it could be possible to support ;)

**Comment by Kahsolt** [comment]
Could you please tell me what extensions about controlnet you'll working with?
I would have an investigation whether it could be possible to support ;)

**Comment by loboere** [comment]
https://github.com/Mikubill/sd-webui-controlnet/issues/417#issuecomment-1484234568

https://github.com/Mikubill/sd-webui-controlnet/commit/f39578a9b0b41c9a41687ed9f8a27a952d176ece

**Comment by Kahsolt** [comment]
Thanks for the discussions, it is a bug on ptravel side, now should have been fixed.
I tested depth and openpose, they work well, canny and others should also do.
Notice me again if anything goes wrong :o

**Comment by enn-nafnlaus** [comment]
> Thanks for the discussions, it is a bug on ptravel side, now should have been fixed. I tested depth and openpose, they work well, canny and others should also do. Notice me again if anything goes wrong :o

Awesome!  Just updated Prompt Travel and will try it out as soon as my GPU is free!  I was stuck on an old version of ControlNet to complete this project:

https://www.youtube.com/watch?v=zUa0pB_TqqM

Prompt Travel works so well with ControlNet!
