### ISSUE TITLE
controlnet travel does nothing

### ISSUE THREAD

**Issue by loboere** [Kahsolt/stable-diffusion-webui-prompt-travel#25]
I put the path of the folder correctly
I press generate but nothing happens

prompt travel latest version
controlnet version 1.1

**Comment by Kahsolt** [comment]
See if there are any console logs, or webui info log right below the preview box?

**Comment by viva-la-v** [comment]
Start up webui with this in my console log:

```
Error loading script: controlnet_travel.py
Traceback (most recent call last):
  File "D:\@\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\@\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\@\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\controlnet_travel.py", line 50, in <module>
    def cfg_based_adder(self:UnetHook, base:Tensor, x:Tensor, require_autocast:bool, is_adapter=False):       
NameError: name 'UnetHook' is not defined
```

**Comment by Kahsolt** [comment]
This  `controlnet_travel.py` works with [https://github.com/Mikubill/sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet).
If you do not need this, it is safe to ignore this error.

I just could not find a better way to check if controlnet exists while silencing errors if it not ;(

**Comment by Kahsolt** [comment]
The ControlNet script updates tooooo rapid, I just merged all update into my hack, now it is tested with controlnet `v1.1.116` and works ok on my machine. You can try again ;)

**Comment by mashb1t** [comment]
![image](https://user-images.githubusercontent.com/9307310/235356554-a3b58fb6-e644-41e7-8f9a-590fce616262.png)
![image](https://user-images.githubusercontent.com/9307310/235356619-2a6594d3-ab2b-43b5-b77a-34d664c34a05.png)

"On branch main
Your branch is up to date with 'origin/main'."

i have https://github.com/Mikubill/sd-webui-controlnet installed and active, still receiving "sd-webui-controlnet not enabled" with the latest version of this module. Is there something i'm missing?
