### ISSUE TITLE
NansException on 2nd image in travel sequence when using ControlNet 

### ISSUE THREAD

**Issue by NicholasMcCarthy** [Kahsolt/stable-diffusion-webui-prompt-travel#32]
Script will generate the first image and then throw the following error on the second image generated during the travel 

```
modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
```

Automatic1111 and other scripts (Controlnet travel, sd-animation, etc) are working fine. Have tried with a number of different models (1.5, realisticvision). Setting the no-half and upcast cross attention to float32 options produced different errors (not related to the script). 

## Versions:
Automatic1111 version: [v1.3.0] 
 python: 3.10.11  
 torch: 2.0.1+cu117  
xformers: N/A  
gradio: 3.31.0  
checkpoint: [e6415c4892]

**Comment by NicholasMcCarthy** [comment]
On further checks, it appears to be related to controlnet.

**Comment by Kahsolt** [comment]
the ControlNet script is updating rapidly and hard to keep up with, I will check it tomorrow...

**Comment by zaderei** [comment]
Have the same issue - either noise generation or NaNs error with controlnet enabled, without runs fine

**Comment by Kahsolt** [comment]
Now the latest version `v3.0` is tested with:

-   [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui): version v1.4.0, tag [v1.4.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.4.0)
-   [Mikubill/sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet): version v1.1.229, commit [eceeec7a7e](https://github.com/Mikubill/sd-webui-controlnet/commit/eceeec7a7e856867de56e26cae9f3e1076480344)

have a try at your ease~
