### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by evanerichards** [Kahsolt/stable-diffusion-webui-prompt-travel#39]
I'm running into the following problem:

```
[ControlNet-Travel] extension Mikubill/sd-webui-controlnet found, ControlNet-Travel loaded :)
*** Error loading script: controlnet_travel.py
    Traceback (most recent call last):
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\controlnet_travel.py", line 45, in <module>
        from manager import run_cmd
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\manager.py", line 12, in <module>
        from PIL.ImageTk import PhotoImage
      File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageTk.py", line 28, in <module>
        import tkinter
    ModuleNotFoundError: No module named 'tkinter'
```

I've gone into my venv and run a python script that confirmed that tkinter IS installed. So I'm not sure what the issue is.

I'm running Auto1111 version: [1.6.0]
python: 3.10.11
torch: 2.0.1+cu118

Any thoughts? Is it possible that prompt-travel is interfering with controlnet somehow?

**Comment by gateway** [comment]
i have to second this.. brand new install with prompt travel and cn.. and its getting me that error as well.. t

**Comment by gateway** [comment]
> I'm running into the following problem:
> 
> ```
> [ControlNet-Travel] extension Mikubill/sd-webui-controlnet found, ControlNet-Travel loaded :)
> *** Error loading script: controlnet_travel.py
>     Traceback (most recent call last):
>       File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\scripts\controlnet_travel.py", line 45, in <module>
>         from manager import run_cmd
>       File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\extensions\stable-diffusion-webui-prompt-travel\manager.py", line 12, in <module>
>         from PIL.ImageTk import PhotoImage
>       File "E:\StabilityMatrix\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageTk.py", line 28, in <module>
>         import tkinter
>     ModuleNotFoundError: No module named 'tkinter'
> ```
> 
> I've gone into my venv and run a python script that confirmed that tkinter IS installed. So I'm not sure what the issue is.
> 
> I'm running Auto1111 version: [1.6.0] python: 3.10.11 torch: 2.0.1+cu118
> 
> Any thoughts? Is it possible that prompt-travel is interfering with controlnet somehow?

did you find any fixes?

**Comment by evanerichards** [comment]
Nope. I'm still getting it every time I boot up auto1111
